### ISSUE TITLE
Js launch but cant add accouts to test it.

### ISSUE THREAD

**Issue by Romarikon** [krm35/dofus-multi#1]

**Comment by krm35** [comment]
You mean when you click on the add account button? If so, then it's normal, it's because I need to handle the cloudflare protection first to add account, but you are supposed to see the accounts you use on the official launcher? Do you see them?

**Comment by Romarikon** [comment]
I dont see any account can you help me to test ur program? discord hellgonoreha

**Comment by krm35** [comment]
yes of course, I'm gonna send you a message.

**Comment by krm35** [comment]
https://github.com/krm35/dofus-multi/commit/e9b16919e226c3c2ad3d2227166ab8bcf2a1e1a8
