### ISSUE TITLE
error from last maj update

### ISSUE THREAD

**Issue by super-gremlin** [krm35/dofus-multi#10]
![error](https://github.com/krm35/dofus-multi/assets/128115036/2d9cf414-6468-4d14-9fc2-bf5d328cbcfd)

**Comment by krm35** [comment]
Hello what is your version? v2.8.0?

**Comment by krm35** [comment]
Try with this version please and tell me if it works

https://github.com/krm35/dofus-multi/releases/download/2.9.0/renommez-moi-svp.zip

**Comment by super-gremlin** [comment]
works, looks like i have to change the language to fr, weirds cause before used to work with english and spanish too

**Comment by krm35** [comment]
you can default to english or spanish by creating a file named lang.txt in the data folder and put:
for spanish:
es
for english:
en

Tell me if everything is fine
