### ISSUE TITLE
cant launch more than 4 accounts

### ISSUE THREAD

**Issue by fiveheadindeeeed** [krm35/dofus-multi#11]
when i try to launch the 5th account i have a anakama launcher not detected can you please address it ?

**Comment by krm35** [comment]
dofus, retro or wakfu?

**Comment by fiveheadindeeeed** [comment]
retro

**Comment by fiveheadindeeeed** [comment]
can i have your discord or something i can reach you with please

**Comment by fiveheadindeeeed** [comment]
hello are you there sir, if you can respond quick i have a limited access of internet please thank you

**Comment by krm35** [comment]
kop9612

**Comment by fiveheadindeeeed** [comment]
i dmd you

**Comment by krm35** [comment]
Fixed in 488f877a24a4e5446183debe4bf1e27744b1d29e
