### ISSUE TITLE
Unhandled exception using 4G connection

### ISSUE THREAD

**Issue by IMagwaI** [krm35/dofus-multi#12]
Bonsoir, l'application fonctionne bien avec un wifi, par contre avec la 4G ca fonctionne pas du tout ca lance la fenêtre du jeu et tu restes coincé sur la popin "Attendre .." et sur la console on a la stack d'erreur suivante.

![image](https://github.com/krm35/dofus-multi/assets/58571715/ae579c1f-ba92-4442-855f-90aade1202b3)

y'a t-il une astuce à cet égard ? merci d'avance

**Comment by krm35** [comment]
Bonsoir, vous avez téléchargé quand l'exe ?

**Comment by krm35** [comment]
J'ai fait une version qui log l'erreur

https://github.com/krm35/dofus-multi/releases/download/2.16.0/renommez-moi-svp.zip

à tester et montrer le message plz

**Comment by IMagwaI** [comment]
d'accord, je te fais un retour

**Comment by IMagwaI** [comment]
voici le retour sur la console 
![image](https://github.com/krm35/dofus-multi/assets/58571715/4a344267-eaec-462c-9064-b1958832ab45)

**Comment by IMagwaI** [comment]
> Bonsoir, t'as téléchargé quand l'exe ?
> 
> T'as le bug depuis quand ?

j'ai repris la dernière version

**Comment by krm35** [comment]
tu avais le bug auparavent ? j'ai l'impression que tu as ajouté ou supprimé le shield récemment sur un compte non ?

**Comment by IMagwaI** [comment]
Oui , je peux me connecter normalement sur le compte sans l'app

**Comment by IMagwaI** [comment]
d'accord

**Comment by krm35** [comment]
Cette release devrait fixer le problème :

https://github.com/krm35/dofus-multi/releases/tag/3.0.0

à confirmer
