### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by S73V3NHawk1ng** [krm35/dofus-multi#21]
wanna get connected using proxy but not working , fix it please <3 thanks

**Comment by krm35** [comment]
retro or d2 ?

**Comment by Halkreen** [comment]
same issue on retro, even with 2 accounts on separate IPs 
First time i'm trying so no idea if it worked before

**Comment by krm35** [comment]
mp me on discord to debug and fix plz kop9612

**Comment by krm35** [comment]
aucun bug détecté après debug
