### ISSUE TITLE
Issue : ”Need to refresh api key”

### ISSUE THREAD

**Issue by Fclxy** [krm35/dofus-multi#22]
When i try connect account with Proxy or another Internet diferent than default with Wifi USB occurs an error.

**Comment by Fclxy** [comment]
![Capturar](https://github.com/krm35/dofus-multi/assets/172556458/e2b2786b-7438-4e50-aabd-bc1ea3f18718)

**Comment by krm35** [comment]
Hello, when u get this u need to add the account using the add account button, tell me if everything is fine.
