### ISSUE TITLE
Error when connecting through 4G

### ISSUE THREAD

**Issue by metita** [krm35/dofus-multi#3]
Basically when connecting, an error appears, does not happen with default IP connection or proxy

![image](https://github.com/krm35/dofus-multi/assets/33007491/5770b4d0-18c0-4da5-b790-e99f4f6fb3d6)
![image](https://github.com/krm35/dofus-multi/assets/33007491/03fb4797-7970-4908-8af2-b566885413f8)

**Comment by krm35** [comment]
I'm gonna check.

Are u able to play with 2 accounts, one with default IP and another one with proxy ?

**Comment by metita** [comment]
Yep.

**Comment by krm35** [comment]
Can you give me your discord nickname to debug that please?

**Comment by krm35** [comment]
https://github.com/krm35/dofus-multi/commit/4cb2468248b52fc99d38dc1ea3de28f23a7eebd4
