### ISSUE TITLE
Aide Utilisation Github krm35

### ISSUE THREAD

**Issue by Neniripsia** [krm35/dofus-multi#4]
Bonjour, je ne parviens pas à utiliser le dofus multicompte sur serveur monocompte sur Dofus retro. Lorsque je lance l'application je peux lancer la premiere fenetre mais lorsque je selectionne le second compte il m'indique une erreure est survenue. Pouvez-vous revenir vers moi SVP?

**Comment by krm35** [comment]
discord ?

**Comment by Neniripsia** [comment]
Oui mon nom de discord est Drneni



Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
