### ISSUE TITLE
dofus-multi

### ISSUE THREAD

**Issue by HoussamT** [krm35/dofus-multi#5]
petit bug je n'arrive plus a lancer un compte depuis un petit moment. Celui du milieu

![image](https://github.com/krm35/dofus-multi/assets/29040085/f96befd0-043a-49e5-9441-3e85ec6c6329)

**Comment by krm35** [comment]
C'est possible que sa clé d'api ait expirée, ça marche avec le launcher classique ?
Connexion via proxy ou 4G ?
Utilisation du binaire renommez-moi.exe ou build du code avec node.JS ?

**Comment by HoussamT** [comment]
launcher classic => OK
connexion 4g et cablé j'ai testé les 2
utilisation du binaire Renommez-moi.exe

**Comment by metita** [comment]
delete all files under data folder, that should work, it happened to me once but not sure how to repro

**Comment by HoussamT** [comment]
@metita  Where is it located?

**Comment by krm35** [comment]
le dossier data est là où tu as le l'exe, tu fermes tout et tu delete le dossier pour tout réinitialiser. Ensuite tu télécharges cette version, c'est la dernière https://github.com/krm35/dofus-multi/releases/download/2.4.0/renommez-moi-svp.zip avec différents bug fix

**Comment by HoussamT** [comment]
Resolu
