### ISSUE TITLE
Compatibilité Wakfu?

### ISSUE THREAD

**Issue by HoussamT** [krm35/dofus-multi#7]
Bonjour est-it possible de rendre le projet compatible avec Wakfu mono?

**Comment by krm35** [comment]
J'ai essayé https://github.com/krm35/dofus-multi/commit/a304c36dcdb92e28d8c30252f9c0376b1d57d8a4 mais il faut que je trouve comment ils identifient les clients de manière unique d'abord.

**Comment by Seitsuo** [comment]
Hello, la compatibilité wakfu avance bien ? Encore merci pour ton travail !

**Comment by krm35** [comment]
Dimanche soir

**Comment by krm35** [comment]
c done.

**Comment by Seitsuo** [comment]
Salut, possible de m'ajouter discord pour 2-3 questions pls ? Discord : shizinu

**Comment by krm35** [comment]
yes
