### ISSUE TITLE
Ne parvient pas à faire fonctionner

### ISSUE THREAD

**Issue by Keke-jpg-max** [krm35/dofus-multi#8]
Hello,

Je suis désolé de te déranger, lorsque j'ouvre l'appli elle se ferme automatiquement, même en admin. 

Je suis sur Windows 10.

ENOENT no such file directory etc....

Je suppose que c'est parce que je suis une buse, mais faut-il faire quelque chose de spécifique pour réussir à lancer l'appli ?

Merci à toi

**Comment by krm35** [comment]
Salut tu peux mettre un screenshot stp sinon donne ton discord pour débug en live

**Comment by Keke-jpg-max** [comment]
Kekettz ou Kekettz#4186
C'est super sympa merci

**Comment by krm35** [comment]
je t'ai add
